spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/fitness-app/protocol/openid-connect/certs

  cloud:
#    config:
#      enabled: false   # disable Config Server for local testing
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE   # service name from Eureka
              predicates:
                - Path=/api/users/**

            - id: activity-service
              uri: lb://ACTIVITY-SERVICE   # service name from Eureka
              predicates:
                - Path=/api/activities/**

            - id: ai-service
              uri: lb://AI-SERVICE   # service name from Eureka
              predicates:
                - Path=/api/recommendations/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080
